### ISSUE TITLE
Getting `Object.entries is not a function`

### ISSUE THREAD

**Issue by trotzig** [Galooshi/import-js#259]
I'm seeing this error after updating to the latest master:

```
⨠ importjs fix app/assets/components/NewLoggedOutHomePage/index.jsx
/Users/henrictrotzig/import-js/build/Configuration.js:102
  Object.entries(RENAMED_CONFIGURATION_OPTIONS).forEach(function (_ref) {
         ^

TypeError: Object.entries is not a function
    at convertRenamedConfiguration (/Users/henrictrotzig/import-js/build/Configuration
.js:102:10)
    at /Users/henrictrotzig/import-js/build/Configuration.js:158:31
    at Array.forEach (native)
    at new Configuration (/Users/henrictrotzig/import-js/build/Configuration.js:155:40
)
    at new Importer (/Users/henrictrotzig/import-js/build/Importer.js:60:19)
    at /Users/henrictrotzig/import-js/build/importjs.js:80:20
    at /Users/henrictrotzig/import-js/build/importjs.js:55:7
    at tryToString (fs.js:415:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:402:12)
→ exit status: 1
```

**Comment by lencioni** [comment]
Ah, of course. We can either rewrite it or bring in this shim: https://www.npmjs.com/package/object.entries
