### ISSUE TITLE
Tests fail in Node v6.0.0+

### ISSUE THREAD

**Issue by trotzig** [Galooshi/import-js#272]
I'm seeing a bunch of these errors when running tests on Node 6.1.0:

```
● Importer › #fixImports › when the last import is removed from a named import › it remov
es the whole import
  - TypeError: Cannot read config file: /Users/henrictrotzig/import-js/.eslintrc.js
    Error: Path must be a string. Received undefined
        at assertPath (path.js:7:11)
        at Object.dirname (path.js:1324:5)
        at module.exports (node_modules/require-uncached/index.js:11:34)
        at loadJSConfigFile (node_modules/eslint/lib/config/config-file.js:161:16)
        at loadConfigFile (node_modules/eslint/lib/config/config-file.js:200:22)
        at Object.load (node_modules/eslint/lib/config/config-file.js:494:18)
        at loadConfig (node_modules/eslint/lib/config.js:64:33)
```

Downgrading to 5.8.0 works.

**Comment by lencioni** [comment]
This seems to happen in Node 6 as well: https://travis-ci.org/Galooshi/import-js/jobs/131898868

**Comment by lencioni** [comment]
eslint depends on require-uncached, which depends on caller-path, which depends on callsites, which under this version of Node is not working as expected. I've updated my local copy of callsites to their latest version on master and that did not resolve the issue. I also tried reproducing this in a node console but was unable to.

This makes me believe that Jest is doing something funny that causes this to happen. I'm going to create a minimal repro and open an issue.

**Comment by lencioni** [comment]
Minimal repro case: https://github.com/lencioni/jest-eslint-node6-bug
Jest issue: https://github.com/facebook/jest/issues/1048

**Comment by lencioni** [comment]
I tried changing our .eslintrc.js files to be .eslintrc files, but this seems to also affect plugins:

```
● Importer › #fixImports › when an unused variable that shares its name with an import exi
sts › it does not display any message
  - TypeError: Cannot read config file: /Users/joe/import-js/node_modules/eslint-plugin-re
act/index.js
    Error: Path must be a string. Received undefined
    Referenced from: /Users/joe/import-js/.eslintrc
        at assertPath (path.js:7:11)
        at Object.dirname (path.js:1324:5)
        at module.exports (node_modules/require-uncached/index.js:11:34)
        at loadJSConfigFile (node_modules/eslint/lib/config/config-file.js:161:16)
        at loadConfigFile (node_modules/eslint/lib/config/config-file.js:200:22)
        at load (node_modules/eslint/lib/config/config-file.js:494:18)
        at eval (node_modules/eslint/lib/config/config-file.js:386:36)
        at Array.reduceRight (native)
        at applyExtends (node_modules/eslint/lib/config/config-file.js:363:28)
        at Object.load (node_modules/eslint/lib/config/config-file.js:525:22)
```

**Comment by trotzig** [comment]
I've temporarily removed 6 from the Travis build: https://github.com/Galooshi/import-js/commit/450d2b26998fd010d68573e4feedf4f9766fd688
