### ISSUE TITLE
"goto module" not working in sublime

### ISSUE THREAD

**Issue by ljharb** [Galooshi/import-js#273]
Got this output, @lencioni asked me to post it:

```
['importjs', 'goto', 'withWindow', '$PWD/spec/javascripts/_helpers/withUserAgent.js']
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 568, in run_
    return self.run(edit, **args)
  File "import-js in $HOME/Library/Application Support/Sublime Text 3/Installed Packages/ImportJS.sublime-package", line 152, in run
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
['importjs', 'goto', 'withWindow', '$PWD/spec/javascripts/_helpers/withUserAgent.js']
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 568, in run_
    return self.run(edit, **args)
  File "import-js in $HOME/Library/Application Support/Sublime Text 3/Installed Packages/ImportJS.sublime-package", line 152, in run
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
['importjs', 'goto', 'withWindow', '$PWD/spec/javascripts/_helpers/withUserAgent.js']
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 568, in run_
    return self.run(edit, **args)
  File "import-js in $HOME/Library/Application Support/Sublime Text 3/Installed Packages/ImportJS.sublime-package", line 152, in run
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
['importjs', 'goto', 'withWindow', '$PWD/spec/javascripts/_helpers/withUserAgent.js']
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 568, in run_
    return self.run(edit, **args)
  File "import-js in $HOME/Library/Application Support/Sublime Text 3/Installed Packages/ImportJS.sublime-package", line 152, in run
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
SublimeLinter: eslint: env.js ['$PWD/node_modules/.bin/eslint', '--format', 'compact', '--stdin', '--stdin-filename', '@'] 
SublimeLinter: eslint: listing.js ['$PWD/node_modules/.bin/eslint', '--format', 'compact', '--stdin', '--stdin-filename', '@'] 
SublimeLinter: eslint: require-npm-run-mocha.js ['$PWD/node_modules/.bin/eslint', '--format', 'compact', '--stdin', '--stdin-filename', '@'] 
SublimeLinter: eslint output:
$PWD/test/require-npm-run-mocha.js: line 1, col 0, Error - Resolve error: Path must be a string. Received null (import/no-unresolved)
$PWD/test/require-npm-run-mocha.js: line 1, col 31, Error - Unable to resolve path to module 'child_process'. (import/no-unresolved)
$PWD/test/require-npm-run-mocha.js: line 4, col 3, Warning - Unexpected console statement. (no-console)
$PWD/test/require-npm-run-mocha.js: line 5, col 3, Warning - Unexpected console statement. (no-console)
$PWD/test/require-npm-run-mocha.js: line 6, col 3, Warning - Unexpected console statement. (no-console)

5 problems 
```

**Comment by trotzig** [comment]
Thanks for reporting this. 

It's a little hard to decrypt this, but I think you're seeing this because the import-js plugin fails to find the `project_path`. Likely because the `file_path` contains `"$PWD"` (unless you added that yourself?). I'll look into it.

**Comment by trotzig** [comment]
I pushed version 0.7.4 which will hopefully fix this. You should be able to update through Package Control  as soon as it has picked up the version change.

**Comment by ljharb** [comment]
Yes, I replaced my actual project dir and home dir with placeholders for the sake of the issue, sorry about that.

Awesome, thanks! This appears to have fixed it!
