### ISSUE TITLE
Use path.isAbsolute for Windows compatibility

### ISSUE THREAD

**Issue by reohjs** [Galooshi/import-js#397]
### Issue

The [`makeAbsolute`](https://github.com/Galooshi/import-js/blob/master/lib/findProjectRoot.js#L18) function already receives an [absolute path](https://nodejs.org/api/path.html#path_path_isabsolute_path) ("C:\path") on Windows but only checks if it begins with '/' and so wrongly tries to convert it with the `path.join` where `process.cwd()` is actually "C:\Users\<username>\AppData\Local\atom\app-1.16.0\resources\app.asar\node_modules\decompress-zip\node_modules\graceful-fs\polyfills.js", turning `pathToFile` into a mish-mash of paths.

For some reason this then causes `findRecursive` to enter an infinite loop.

### Fix 

Replace `pathToFile.startsWith('/')` with `path.isAbsolute`

____________________

Steps to reproduce:

1. Activate any of the 3 commands
 
**Atom**: 1.16.0 ia32
**Electron**: 1.3.13
**OS**: Microsoft Windows 7 Professional (64-bit)
**Thrown From**: [atom-import-js](https://github.com/galooshi/atom-import-js) package 0.6.1

### Stack Trace

Uncaught RangeError: Maximum call stack size exceeded

```cmd
At path.js:64

RangeError: Maximum call stack size exceeded
    at String.slice (native)
    at normalizeStringWin32 (path.js:64:22)
    at Object.normalize (path.js:403:14)
    at Object.join (path.js:527:18)
    at findRecursive (/packages/atom-import-js/node_modules/import-js/build/findProjectRoot.js:28:10)
    (then the above line repeated as many times as possible)
    at findProjectRoot (/packages/atom-import-js/node_modules/import-js/build/findProjectRoot.js:39:10)
    at withModuleFinder (/packages/atom-import-js/lib/withModuleFinder.js:6:26)
    at importWord (/packages/atom-import-js/lib/import-js.js:112:3)
    at /packages/atom-import-js/lib/import-js.js:150:33)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/app.asar/src/atom-environment.js:1185:28)
    at EventEmitter.outerCallback (/app.asar/src/application-delegate.js:325:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

**Comment by trotzig** [comment]
Thanks for the report @reohjs! That's embarrassing, sorry for the inconvenience. Is there any chance you'd be willing to file a PR fixing this issue? I don't have access to a Windows machine at the moment.

**Comment by reohjs** [comment]
Done #398
