### ISSUE TITLE
can not Cannot find module sqlite3

### ISSUE THREAD

**Issue by wsdjeg** [Galooshi/import-js#481]
I get error like:

```
module.js:544
    throw err;
    ^

Error: Cannot find module '/home/wsdjeg/.npm-packages/lib/node_modules/import-js/node_modules/sqlite3/lib/binding/node-v59-linux-x64/node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/wsdjeg/.npm-packages/lib/node_modules/import-js/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
```

when run `importjs  start --parent-pid 10639`.

but before this, I have installed the import-js  via `npm install -g import-js`

ref: https://github.com/SpaceVim/SpaceVim/issues/1098

**Comment by wsdjeg** [comment]
This works well for me https://github.com/TryGhost/Ghost/issues/5911#issuecomment-319256067
